export const WORLD_WIDTH_PX = 512;
export const WORLD_HEIGHT_PX = 480;
const NO_MANS_LAND_PX = 32;

export const WORLD_BOUNDARY_NORTH = NO_MANS_LAND_PX;
export const WORLD_BOUNDARY_EAST = WORLD_WIDTH_PX - NO_MANS_LAND_PX;
export const WORLD_BOUNDARY_SOUTH = WORLD_HEIGHT_PX - NO_MANS_LAND_PX;
export const WORLD_BOUNDARY_WEST = NO_MANS_LAND_PX;
